### ISSUE TITLE
Issue of TJ exercise 5-3

### ISSUE THREAD

**Issue by AlexHYF** [wx-csy/Problem_Solving_III#1]
Some of the answers need simplification.
i.e. (c) can be writen as (16)(12)(24)
while the simplification of (d) is a little complicated and I'm not sure about my answer.
Thx.

**Comment by AlexHYF** [comment]
my answer for (d) is (21)(71)(61)(41)

**Comment by wx-csy** [comment]
The problem itself does not require simplification, and I decide not to simplify.
To verify the correctness of your answer, you may perform the permutation on some set of numbers, and check whether the simplified version and the original version give the same answer.
